# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: "Sex Equality and Equity Network"
description: "Sex Equality and Equity Network"

short_url: 'seen-network.uk'
google_analytics: 'G-M68CLZWFBN'
# disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /
url: "https://seen-network.uk" # the base hostname & protocol for your site, e.g. http://example.com

# Permalinks
# permalink: /:title
permalink: /posts%2f:year-:month-:day-:title/
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: seen-network
repo: seen-network.github.io
branch: main
relative_source: ../
destination: ./_site/
# production_url:  https://seen-network.uk/
# source_url:  https://github.com/seen-network/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
  - drafts

defaults:
  # Posts defaults
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts # Apply the default values below only to posts
    values:
      cover: 'assets/images/white-background.jpg'
      logo: 'assets/images/seen-logo-light.png'
      navigation: True
